<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Biblioteca Shelby</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link 
      rel="stylesheet" 
      href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" 
      integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" 
      crossorigin="anonymous"
    />

    <link rel="stylesheet" href="../Include/css/estilo.css">
    
    <style>
      .page-header {
        display: flex;
        justify-content: space-between;
        align-items:center;
        margin: 32px 0;
      }
      </style>
      <script>
function ConfirmarDelete(){
  var x = confirm("Deseja realmente excluir?");
  if (x)
      return true;
  else
    return false;
}
</script>
  </head>

  <body>